modLoader="javafml"
loaderVersion="[32,)"
license="All rights reserved"
issueTrackerURL="https://github.com/teamauroramods/NotWhatItSeems/issues"

[[mods]]
    modId="notwhatitseems"
    version="${file.jarVersion}"
    displayName="Not What It Seems"
    displayURL="https://discord.gg/VzXSCFp"
    logoFile="logo.png"
    authors="Team Aurora"
    description="Adds static versions of blocks for decoration, as well as a few oddities."

[[dependencies.notwhatitseems]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.10,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.notwhatitseems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"